### PR TITLE
Fixing display issues on bigger displays + speedometer

### PR DESCRIPTION
**Pull request by LX8369**

### CODE REVIEW

**Comment by aeolus-1** [comment]
I know what you mean with the issues on bigger screens and what youve done isnt enough
those screen bounds also change view area and that limit limits how much you can see of the map
itll need more complex stuff than that
ill work on it

the speedomder's cool
I suggest an fps counter as well

**Comment by LX8369** [comment]
yeah i can make a fps counter

**Comment by aeolus-1** [comment]
ill just give you moderation itll be eiaser
just dont change anything on a large scale without checking with me

**Comment by aeolus-1** [comment]
just dont change anything with my approval

speedoter is fine
and fps counter

**Pull request closed without merging**
